### ISSUE TITLE
SA, Admin - Task - Unable to add task for particular section.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#113]
1- Open the Admin Panel
2- Go to the Task Module
3- Add Section
4- Now, Click on the dots for Task Section
5- Click on the Add Task
6- Check 
A section is getting blank.

https://user-images.githubusercontent.com/88538559/230890662-d93906bd-ee87-4e98-bacb-07cbc6e0b9db.mp4

**Comment by yash220185Ith** [comment]
its a bug when, we now go from sections, add task then there will be no create and add another task functionality now.
