### ISSUE TITLE
SA, & Admin - Rating - Change Project Name then User name field should be reset & Can't select old date & Correct the text message for Task section.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#117]
1- Open the panel
2- Go to the rating section
3- Click on the Add rating
4- Select Project & User
5-Now, Change the Project name 
then the User field should be blank.
6- Select 10, 20 years Date for rating.
please restricted
7- click on the Submit button
8- Check the Alert message for the Task section
There is showing "User name is required !!".

https://user-images.githubusercontent.com/88538559/230896828-51a85243-e23c-4eec-9af8-b19e32284809.mp4

![image_2023_04_10T11_48_13_951Z](https://user-images.githubusercontent.com/88538559/230896833-e286f350-0ffb-4633-93e4-78cac72fce1e.png)

**Comment by yash220185Ith** [comment]
now the min date set is   min="2023-04-01"
Error msg updated,
And for user the user selected one is of the selected project only.
