### ISSUE TITLE
Contributor  - Task - Directly click on the Export Task. Panel is logging out & Blank file is getting downloaded.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#127]
1- Go to the Task Module
2- Click on the Export button without selecting any filter
3- Now Check
4- the panel is logging out
5- Excel is getting Blank.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b467ff91-a4e1-4f67-b287-a111b56b5b46

**Comment by Ayushjaisgit** [comment]
Sir Export Data functionality is only allowed to SUPERADMIN, ADMIN, and LEAD and this is the reason that Excel sheet is downloading and getting no data in it, 

We'll update it by removing the Export button in the Contributor role and other roles except those mentioned above

**Comment by amanQA** [comment]
Now, the Export Button is not showing in the Lead, Contributor Panel.
