### ISSUE TITLE
Contributor -  Add Task for meeting from the Section & edit task. now complete task. Now, Team lead is able to give rating task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#129]
1- Add Task
2- Select Meeting from the section 
3- Create a task & Add
4- now, edit the task
5- Select Misc in Section 
6- Select Misc type
7- Save
8- Complete Task
9- Now, open the Lead, Admin & super-admin panel
10 - Give a rating & check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/ae322d8c-dee8-4951-ba19-ad0d28c80e86

**Comment by Ayushjaisgit** [comment]
Resolved Sir!

**Comment by amanQA** [comment]
not resolved yet, facing the same.

**Comment by amanQA** [comment]
resolved
