### ISSUE TITLE
Lead, Admin & superadmin  - Not able to reopen the completed task. there is showing can't edit completed task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#132]
1- Go to the Lead panel
2- Reopen the task
3- Check 
there is a showing  can't edit the completed tasks.

![image_2023_06_02T08_21_12_843Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/78bb6ccb-8f1b-4c87-adf8-baa7efc3fde9)

**Comment by Ayushjaisgit** [comment]
Resolved Sir!

**Comment by amanQA** [comment]
resolved
