### ISSUE TITLE
Add task - Estimate Time should be passed in Given Format like 02:59. 

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#140]
1- Add task
2- Create a Task 
3- Fill Time like 02:60
this is the wrong format.
Please check

![image_2023_06_13T08_09_54_534Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/77184c39-88da-4450-969b-09f613f5b8ab)

**Comment by hamzam999** [comment]
fixed
