### ISSUE TITLE
If I create a task by filling in only the lead, task title, and description without selecting the assignee and due date, and then edit the same task, the assignee and due date will be pre-selected by default.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#141]
1- Go to the Task Module
2- Create a Task
3- Fill  lead, task title, and description
4- Click on the Create 
5- Now, Click on the Edit Button
6- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/27a5c55d-f324-475a-b601-d660b450f86a

**Comment by hamzam999** [comment]
This is the case only in the role of contributor

**Comment by hamzam999** [comment]
This is the case only in the role of contributor
