### ISSUE TITLE
profile - After updating my profile, I logged out and logged back in, but my profile is appearing blank.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#142]
1- Go to the profile Section
2- Update Profile
3- logout panel
4- login panel
5- profile is getting Blank.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/96734644-5077-40a6-b582-7680f22c1b43

**Comment by hamzam999** [comment]
In correct response from backend

**Comment by hamzam999** [comment]
resolved from backend
