### ISSUE TITLE
When opening any module, the logout button always remains highlighted in blue color. Please correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#144]
1- Open the T-pro panel
2- Check Logout Button

![image_2023_06_13T09_35_48_809Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/e5287f1a-7c8b-4b28-b3d2-59e2d87575fe)

**Comment by Adityanottysingh** [comment]
Resolved
