### ISSUE TITLE
Not able to view verify comment in View Task page.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#146]
1- Open the Rating Module
2- Click on the Current date 
3- Now, Click on the Task name
4- Check and verify the Comment

![image_2023_06_13T09_35_48_809Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/5755c3aa-7524-41d6-b536-edb4694c920d)

**Comment by hamzam999** [comment]
verified comments added
