### ISSUE TITLE
Correct the UI of Rating Box. somehere is showing small & large. it should be shown in  at height & width.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#147]
1- Open the Rating module
2- Check the Rating Box

![image_2023_06_13T09_39_24_620Z (1)](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/0cf08511-eeaf-4b28-8170-a417da131dc5)

**Comment by hamzam999** [comment]
resolved
