### ISSUE TITLE
Fill Comment for verify Task & Once the task is verified, the comment associated with the previous task should not be displayed by default another task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#149]
To verify a task, follow these steps:

1- Fill in the comment for the task.
2- Click on the "Verify" button to verify the task.
3- Now, Open another task & check
Once the task is verified, the comment associated with the previous task should not be displayed by default in the new task.1-

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/1c0b22f4-0909-4530-8c96-d27d136040db

**Comment by Adityanottysingh** [comment]
resolved
