### ISSUE TITLE
Login Page -An alert message should be shown. when, Directly click on the Login button or login with Wrong credentials.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#15]
1- Open Tea Pro
2- Directly click on the Login button & check
3- Fill the wrong credential 
4- Click on the Login button
An alert message should be shown.

https://user-images.githubusercontent.com/88538559/228529044-ca78aef9-50aa-49fe-a1a3-1e20dc9e6f23.mp4

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved

**Comment by amanQA** [comment]
Resolved & Closed
