### ISSUE TITLE
Rating - Team view button is not working properly. Click on the button. it's taking too long time for Navigating the actual page.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#150]
1- Go to the Rating Module.
2- Click on the Team View button
3- Check

![image_2023_06_13T11_10_02_945Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/4617b614-b417-4d31-afcf-a396f25c0e51)

**Comment by hamzam999** [comment]
not found in my system
