### ISSUE TITLE
Assign manager should be shown in Team memebr list & Contributor completed his task but when Manager trying to Give rating. there is showing no task found. rating is updating without task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#151]
1- Create a Task by Contributor
The Lead is Mohit.
2- Now, Complete his task
3- Now, Assign the Manager
4- Go to the Rating Module
5- Click on the Current Date
there is showing No task found.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/864b5857-5078-4414-b22b-14ff79d2717e

**Comment by hamzam999** [comment]
resolved
submit button disabled if no tasks are found
