### ISSUE TITLE
Contributor - Profile Completed. But Login multiple times & showing profile section multiple times. Please correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#152]
1- Open the Contributor panel
2- Login app
Showing Profile Section
3- Complete the profile with all fields
4- Logout & login Panel
5- Check 
The profile  section is showing on multiple logins.
![image_2023_06_27T05_59_47_732Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/2740f3c4-0c1a-433d-b243-db3fdd85d8ab)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
