### ISSUE TITLE
Contributor-  Create & add another task -  Create Task & Click on the Add another Task then Estimate time should be reset.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#154]
1- Go to the contributor panel
2- Add Task & Click on the Add another Task Button.
3- Check 
The estimated time should be reset.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b34ca48a-7b5c-4fa3-af6a-082f289dc6fe

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
