### ISSUE TITLE
Contributor - Project - Correct the alignment of Overdue, completed, ongoing & total task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#156]
1- Go to the Project module
2- Check the alignment of Task details.

![image_2023_06_27T06_31_38_519Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/e7fbc5e8-d7ef-4bcf-ac29-983f08e29cea)

**Comment by amanQA** [comment]
resolved

**Comment by ghost** [comment]
resolved
