### ISSUE TITLE
Contributor  -  Task - apply filter. data is not showing.  loader is loading ony too long times.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#157]
1- Go to the Task Module
2- Apply filter
3- Check 
The loader is loading only too long times.
4- Edit Link & go to the Dashboard
5- Now, Again go to the task Module
6- Check Loader is loading.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/2e2819d9-b6d1-4119-b5df-0f1840b32170

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/7ac7ec1d-b810-4466-9ac8-b1f4a169b5d3

**Comment by hamzam999** [comment]
resolved!

**Comment by amanQA** [comment]
resolved
