### ISSUE TITLE
Login Page - Drop & drag Tea logo in the Link Section then Logo image is opening. please restrict this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#16]
1- Open Tea Pro
2- Drop & drag Tea pro logo
3- Check

https://user-images.githubusercontent.com/88538559/228529568-b299429b-2aa1-4dad-91ff-2784a114f2bc.mp4

**Comment by chandansinghdesigner** [comment]
#resolved
