### ISSUE TITLE
Manage Role -  verify task is not showing in the manager Panel.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#161]
1- Create a Task from the Contributor panel
2- Verify the Task from the Lead panel
3-Now, go to the Manager Panel
4- Check task is not showing there.

![image_2023_06_27T07_30_37_482Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/21e30428-38fc-4a4a-8ede-fdc43369040b)

**Comment by hamzam999** [comment]
Fixed from backend!
TO fix it for current leads (existing users) all projects have to be re assigned!

**Comment by amanQA** [comment]
resolved
