### ISSUE TITLE
manager  Role - Nothing is showing in Manager Role.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#162]
1- Open the Manger panel
2- Check all modules
Data is not showing.

![image_2023_06_27T07_40_50_898Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/fd9afc0e-1849-451f-a388-0b3a5dff70ee)

**Comment by hamzam999** [comment]
fixed form backend.
TO fix this for current users (lead) projects have to be reassigned!

**Comment by amanQA** [comment]
Resolved
