### ISSUE TITLE
Rating is not updating inAssigned & lead Panel.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#164]
1- Go to the Lead panel
2- Create a Task
3- Complete Task
4- Go to the Lead Panel 
5- verify Task
6- Now, Go to the Mamger panel
7- Give a Rating
8- check the Rating in the view Task.

![image_2023_06_27T08_19_51_575Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/4fadafc6-4687-4d9b-91a7-2df506e4a50b)
![image_2023_06_27T08_19_22_387Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/389bf11b-cd7f-4552-8cd5-ec0aec780661)
![image_2023_06_27T08_19_12_108Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/df7581a3-a7c0-44cf-8c9e-6e3a56ba835a)

**Comment by Adityanottysingh** [comment]
resloved in new update we are giving rating day wise not the task wise

**Comment by amanQA** [comment]
resolved
