### ISSUE TITLE
Admin/SuperAdmin -  Task - Apply Search filter. blank pop-up is showing.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#168]
1- Go to the admin/Super-admin panel
2- Open the Task module
3- Apply filter
4- Check

![image_2023_06_27T09_26_39_500Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/121c294e-a604-4eb7-9b61-d9a31f80c2b6)

**Comment by hamzam999** [comment]
resolved

**Comment by amanQA** [comment]
resolved
