### ISSUE TITLE
Admin/SuperAdmin -  wrong data is showing for Free resource.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#169]
1- Go to the admin/SuperAdmin panel
2- Open the Dashboard
3- Check user analytics
There is showing "No user is free!".

![image_2023_06_27T09_42_51_352Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/94e2ecc9-c2ed-4c2f-9c95-e1462872ee5a)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
