### ISSUE TITLE
Login Page- Please correct the password(eye icon) View & hide functionality. if Eye is open then password is hiding & if eye is close then password is showing there.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#17]
1- Open Tea Pro
2- Fill the password
3- Open the Eye icon & check
if the eye opens then the password should be visible.
4- Now, Close the Eye icon & check
if the eye is 

https://user-images.githubusercontent.com/88538559/228530545-d7569950-98ec-4418-b789-969eec771e4c.mp4

closed then the password should not be visible.

**Comment by chandansinghdesigner** [comment]
Resolve

**Comment by amanQA** [comment]
resolved
