### ISSUE TITLE
Lead/Admin/SuperAdmin - Reopen Task & click on the View Task here. 404 Not found is showing there.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#171]
1- Go to the Lead/Admin/SuperAdmin Panel
2- Reopen the task
3- Now, Click on the View task here link text
4- Check

![image_2023_06_27T11_09_31_097Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/5dcfcf73-5833-464f-aa34-22630ba579ec)
![image_2023_06_27T11_09_22_427Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/16391ae5-4093-4f56-b8d9-baee5751d95f)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
View task here Text remove successfully.
