### ISSUE TITLE
Login Page - Unable to click on the username & password Field before & after 1st & 2nd character. cursor should be blinking. please correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#18]
1- Fill Username & password
2- Now, click on the Username & Password field before & after 1st & 2nd Character.

https://user-images.githubusercontent.com/88538559/228531090-2544dc4d-b599-4af1-9af1-795bcc3c2258.mp4

**Comment by yash220185Ith** [comment]
working fine my side.

**Comment by amanQA** [comment]
resolved & closed
