### ISSUE TITLE
Contributor -   Task should not be create without Estimated time.Estimated Field is required. Contributor can't perform any ctivity on the Page loading time like Can't close the pop-up of task creation & scroll the Page etc.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#180]
1- Create a Task from the Dashboard & Task Module
2- Directly click on the Create button
3- Check all required fields

4- Fill details & submit
The loader is loading. 
5- Click on the Close icon on page loading time or try to perform any other activity.
6- Please restrict activity on the page loading time.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/af204f44-87e5-40bc-8599-3b99fa6d7aa6

**Comment by hamzam999** [comment]
done

**Comment by amanQA** [comment]
resolved
