### ISSUE TITLE
Contributor -  Not  able to edit Estimate Time for ongoing task.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#181]
1- Create a Task
2- Fill all details like Estimate time also.
3- Create a task
4- edit the same task on the ongoing stage
5- Change Estimated time only
6- Check
estimated time is not getting saved.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/c3e1d9c4-8f62-4253-93bb-d95210fa8712

**Comment by hamzam999** [comment]
resolved. estimated time will be blank

**Comment by amanQA** [comment]
resolved
