### ISSUE TITLE
Contributor -  Create 2 task at a same time. then Estimate time field data should be reset.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#183]
1- Go to the Task Module 
2- Create  2 tasks at the same time
3- Check
The estimated time should be reset.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/f8d8682b-6c05-400a-ac42-a8244370ce30

**Comment by hamzam999** [comment]
done

**Comment by amanQA** [comment]
Resolved
