### ISSUE TITLE
The "Estimated Time Required" field is shown when creating a task, but sometimes it doesn't appear as a required field.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#184]
1- Go to the Task Module
2- Create a Task
3- Directly click on the Create button
4- Check All Required Fields
5- Again follow the same process
6- Check Now, Estimate time not showing as the required field.

![image_2023_07_03T08_17_25_215Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/71c7f050-d82e-4a04-a5cd-ec52726cb1c9)
![image_2023_07_03T08_17_01_139Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/52fbb547-bf36-4186-83d6-6c6b08d26c6f)

**Comment by hamzam999** [comment]
resolved!

**Comment by amanQA** [comment]
resolved
