### ISSUE TITLE
Lead/Admin/super/Admin - Data should be shown on the behalf of selected Filter. Verify task & Check Filter.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#185]
1- Go to the Dashboard
2- Apply filter
3- Verify Task
4- Now, Check the filter

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/42de5ab2-4d30-4ed0-9d31-d41a46e68c60

**Comment by hamzam999** [comment]
resolved!
