### ISSUE TITLE
Contributor/Lead/Admin/Superadmin -  Reopen task & edit task(not started). Code is breaking.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#189]
1- Reopen the task from the leadAdmin/SuperAdmin panel
2- Go to the Dashboard 
3- Edit Tasks from the Teamwork/Overdue
4- Now, Login to the Contnributor panel
5- Go to the Task Module
6- Edit task 
7- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/6fc29300-0f2f-4f59-9225-54a2ac1159d7

**Comment by Ayushjaisgit** [comment]
Resolved!

**Comment by amanQA** [comment]
Resolved
