### ISSUE TITLE
Dashboard - Click on the Tea pro logo. then, it should be redirecting on the Dashboard page.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#19]
1- Open the Tea Pro app
2- Go to any module
3- Now, Click on the Tea Pro logo on the top of the left side.
it should be redirected to the Dashboard page.

https://user-images.githubusercontent.com/88538559/228533488-d617dcf8-d434-49e8-bd02-229164438278.mp4

**Comment by yash220185Ith** [comment]
Resolved.

**Comment by amanQA** [comment]
Resolved
