### ISSUE TITLE
Admin/Super-Admin -  When adding a new user, a "Resend Email" button should be displayed on their card until the user is verified. After verification, the "Resend Email" button will change to "Add Manager." Once the manager is added, the button will change to three dots.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#190]
1- Add Team
2- Added user should be shown on the card
3- Resend Email button should be shown.
after verifying the user on the panel
Resend Email button should be changed to Add Manager button.
4- Add a manager
after that button should be converted into 3Dots.

![image_2023_07_03T10_04_20_710Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/a6b04860-6000-4e42-a55c-1cf2925bbb79)

**Comment by Adityanottysingh** [comment]
assigned to hamza

**Comment by hamzam999** [comment]
resolved!

**Comment by amanQA** [comment]
resolved
