### ISSUE TITLE
Contributor/Lead/Admin/Super-Admin - Unable to give rating. In the Rating Module, the lead's team is not being displayed. However, when applying the date filter for the previous month, the lead's team is being shown.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#191]
1- Go to the Rating Module
2- Lead's Team is not visible 
3- Apply the date filter of the Previous Month
4- Check there

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/4f2b578f-8eb0-47df-9c5c-f7bfa22c1470

**Comment by Adityanottysingh** [comment]
Assigned to Ayush

**Comment by amanQA** [comment]
Resolved
