### ISSUE TITLE
Admin/Super-Admin - Can't delete & archive project. Please check.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#193]
1- Create a new Project
2- Add 1 task only
3- close the Task
4- now, archive the Task
5- Check
6- Now, delete the Task
7- Check

![image_2023_07_03T12_13_58_127Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/a1abb347-40e2-41cf-a8b1-0b793cd9cd13)
![image_2023_07_03T12_13_37_470Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/4f55724f-e9a9-46ee-8442-d41b0282b3eb)

**Comment by Adityanottysingh** [comment]
Assigned to ayush

**Comment by hamzam999** [comment]
any project with a task will not be deleted

**Comment by amanQA** [comment]
Resolved
