### ISSUE TITLE
When  try to change the status of the task from not started to ongoing, on hold from  the dashboard, it is showing 'Task already verified'.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#197]
1- Go to the Dashboard
2- Change the status of the Task from the Dashboard
3- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/616106b8-dac6-4c3d-915f-b8b43bbd9f8c

**Comment by Adityanottysingh** [comment]
this is older data

**Comment by Adityanottysingh** [comment]
try to change the status on new-added task

**Comment by amanQA** [comment]
not resolved

**Comment by amanQA** [comment]
resolved
