### ISSUE TITLE
Mention comment in completed Task. there is showing B is not a function. If directly click on the post button. showing send all required data field. please correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#199]
1- Go to the Dashboard
2- Mention Comment in Completed Task
3- Check

![image_2023_08_28T06_05_39_733Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/e6af630b-73a8-496a-bc32-22a961a1f631)

![image_2023_08_28T06_08_15_052Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b3da4abd-1f0b-4461-a3dd-e80ab10a378d)

**Comment by amanQA** [comment]
now,  mention the comment in the completed task then no alert message is showing.

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/00a7308a-651c-43cb-9a32-65bf851ba6de

**Comment by Adityanottysingh** [comment]
loader is showing there

**Comment by amanQA** [comment]
ok. Resolved
