### ISSUE TITLE
Task - While trying to add a task, the section field is marked as required, but the alert message is not appearing.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#202]
1- Go to the Task Module
2- Click on the Add Task 
3- Directly click on the Create button
4- Check

![image_2023_08_28T06_16_49_325Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/277147aa-e06b-4349-9e23-1eb49803b019)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
