### ISSUE TITLE
Task -  Add Task from the task & Select Section. Code is breaking.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#203]
1- Go to the task Module
2- Add task
3- Select Section
4- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/72b19848-a4bf-409e-ac85-7db457cc935d

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
