### ISSUE TITLE
Rating - Manage Space Between months & filter. please watch video& Correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#205]
1- Go to the Rating Module
2- Check Filter

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/803fa905-83fc-4646-88b9-c450e0316b21

**Comment by Adityanottysingh** [comment]
this is an responsive issue

**Comment by amanQA** [comment]
resolved
