### ISSUE TITLE
Profile -  Reset password -  Back button is not working.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#208]
1- Go to the profile 
2- Click on the Reset Password
3- Click on the Back button
4- Check

![image_2023_08_28T07_45_45_820Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b12d5a6b-3236-4483-95f9-9d7459523739)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
Resolved
