### ISSUE TITLE
Task -  When I select a date range in the filter, the UI is getting distorted, and the filter reset functionality is also not working.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#210]
1- Go to the Task Module
2- Apply filter of Date range
3- Click  on the Date
Check UI
4- Now, Close the Filter pop-up
5- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/98fbfe1e-b356-48bc-abfd-9bac8de77ba0

**Comment by amanQA** [comment]
not resolved

**Comment by vijayith** [comment]
@Adityanottysingh Filter UI and Reset filter is fixed... but Clear button disappears when we close popup on click outside... and reappears when be open .... please look into it....

**Comment by amanQA** [comment]
Resolved
