### ISSUE TITLE
Task -  Correct the UI of Edit button & Click on the Edit button. Code is breaking.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#212]
1- Go to the Task Module
2- Open Sections
3- Check the edit Button
4- Now, Click on the Edit Button

![image_2023_08_28T08_55_56_508Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/ec8bf918-bb1d-47d4-ade6-c86acf20faaf)

**Comment by Adityanottysingh** [comment]
resolved the functionality part

**Comment by amanQA** [comment]
Resolved only functional part.

**Comment by amanQA** [comment]
Resolved functional & UI Part both
