### ISSUE TITLE
Lead -  Unable to edit Completed Task. code is breaking. please correct this.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#213]
1- Open the Lead panel
2- Go to the Dashboard
3- Now, go to the Teamwork section
4- Edit Task 
5- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/dce104a5-afa7-4bfe-a94d-936f035a2a1c

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
