### ISSUE TITLE
Lead - Dashboard - Click on the add(+) team work button. code is breaking.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#214]
1- Open the Lead Module
2- Go to the Dashboard 
3- Scroll the Page
4- Click on the Add Teamwork  button
5- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/6a4672a1-d82c-4dfb-8405-7a293ed9b6b6

**Comment by Adityanottysingh** [comment]
removed the add task from team-work , because we have already given add task button on dashboard

**Comment by amanQA** [comment]
+ button has been removed successfully.
