### ISSUE TITLE
Lead - Dashboard - Go to the day filter, then select the week filter, and click on 'Previous' or 'Next'. After that, select the day filter and check. Both filters should be reset.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#215]
1- Open the Lead Panel
2- Go to the Dashboard
3- Select the Day filter in Teamwork
4- Now, Select the week
5- Click on the Pre or Next week button
6- Now, Select the Day
The filter should be reset.
7- Now, Select week
8- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/744792d6-c5c0-4352-b60d-fca0a0b16503

**Comment by Adityanottysingh** [comment]
need disscusion

**Comment by vijayith** [comment]
On Hold...
