### ISSUE TITLE
Lead - Dashboard/Project/Task  -  Refresh the Module. there is showing refreshing list.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#216]
1- Go to the Dashboard
2- Refresh the page
3-  Check
![image_2023_08_28T10_29_39_016Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b11bada4-644a-4833-bd90-d405bfd08154)

![image_2023_08_28T10_30_05_365Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/e7250ff8-c50d-496b-84c8-744503b7fdb5)

**Comment by Adityanottysingh** [comment]
need disscution

**Comment by amanQA** [comment]
resolved
