### ISSUE TITLE
Super Admin - Dashboard -  Open any Module showing Refreshing list & Unable to add Task from the Dashboard. code is breaking.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#221]
1- Open the super Admin panel
2- Go to the Dashboard module
3- Click on the User Analytics & show all projects.
4- Check
There is showing Refreshing list.

![image_2023_08_29T05_07_01_493Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/8570fc0d-2264-498d-9732-ce495b743926)
![image_2023_08_29T05_07_10_079Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/7d916129-e39d-489f-ad22-8047181dd213)

**Comment by Adityanottysingh** [comment]
Resolved the add-task feature / refresh list is still pending

**Comment by amanQA** [comment]
Resolved
