### ISSUE TITLE
Super Admin - Dashboard -  Export file from the Project. there is showing res is not defined.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#222]
1- Go to the Dashboard
2- Click on the Project Name
3- Export file
4- Check

![image_2023_08_29T05_09_13_065Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/2157a776-c43d-4cd8-858c-3266a430790e)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved

**Comment by amanQA** [comment]
resolved
