### ISSUE TITLE
Super Admin - Projects -  Filters -  Unable to select project name.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#224]
1- Go to the Project Module
2- Click on the Project Name
3- apply filter
4- Check

![image_2023_08_29T06_21_12_486Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/20977830-ab9b-439a-827b-47df2d251a66)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved

**Comment by amanQA** [comment]
Resolved
