### ISSUE TITLE
Query - Super Admin -  Rating - If a user has been given a 0 rating or marked as Absent, the Task pop-up is displaying blank.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#225]
1- Go to the Rating Module
2- Give 0 Rating
3- Check
4- Mark as absent
5- Check

![image_2023_08_29T06_49_39_369Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/af41e57e-0b35-4f2e-a338-75b5b11ad51e)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
