### ISSUE TITLE
Super Admin -  Team - Add new Team member - Unable to open set password link.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#228]
1- Go to the Team Module
2- Add a new Team member
3- Open Mail & link
4- Check

![image_2023_08_29T07_21_32_818Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/9f506b79-1587-4bac-9b6f-8e926c6b9be7)
![image_2023_08_29T07_21_18_282Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/b756e043-a5c5-4b3b-967c-57986489abb5)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
