### ISSUE TITLE
Super Admin - Profile - Reset password - Facing issue in Reset password. there is showing 2 alert messages at a same time. Back button is not working & page is not showing properly.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#230]
1- Go to the profile Section
2- Click on the Reset password
3- Change password & check
4- Check the Back button
The button is not working.

![image_2023_08_29T07_59_16_515Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/3da0150e-1d20-408e-ba60-91aff49355e8)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
