### ISSUE TITLE
Query - Admin - Rating - name is showing by green color & Correct table of Rating module when scroll the table.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#231]
1- Go to the Rating module
2- Check Coloring & Alignment

![image_2023_08_29T09_40_04_418Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/678741ab-1b62-4960-a8d3-d4754d4bfe36)

**Comment by vijayith** [comment]
Green color shows team member.

**Comment by amanQA** [comment]
resolved
