### ISSUE TITLE
Project -  A project should not be assigned without selecting a name.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#236]
1- Go to the Project Module
2- Click on the Assign project
3- Select Role & Name
4- Now, Select another Role
So, the User name field is getting blank on the Behalf of Role.
5- Click on the assign button
6- Check

https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/157f0557-8d3d-4cfe-9d39-21d1de571355

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
not resolved

**Comment by amanQA** [comment]
Resolved
