### ISSUE TITLE
Task -  Filter & Export button is not working properly.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#240]
1- Go to the Task module
2- Click on the Filter/Export button
3- Check

![image_2023_08_31T10_35_08_195Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/317eef8d-9a65-433b-ab6c-c5d8ff42f87d)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
not resolved
