### ISSUE TITLE
task -  Delete  section button is not working.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#244]
1- Go to the Task Module
2- Click on the dots
3- Click on the Delete Section button
4- Check

![image_2023_09_04T11_40_16_342Z](https://github.com/ITH-Pros/ith_tea_pro-frontend/assets/88538559/94f935dc-e475-41d5-86c7-c48efa0b46f9)

**Comment by Adityanottysingh** [comment]
resolved

**Comment by amanQA** [comment]
resolved
