### ISSUE TITLE
Query - Profile - Sometimes, login with Superadmin. then Profile section is opeing By-default. is it any feature or Bug.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#25]
1- Login with the Superadmin panel
2- Check profile detail page is showing by default.
![image_2023_03_30T04_49_05_440Z](https://user-images.githubusercontent.com/88538559/228736731-5ce999d5-35bc-48da-aab8-88e53cecab8e.png)

**Comment by Adityanottysingh** [comment]
if user is login first then profile section is visible and if user skip or update that profile section then it will not visible
