### ISSUE TITLE
Profile - If Profile is not uploaded. then , there should be shown upload profile Picture. Add limit in all fields.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#26]
1- Go to the Profile section
2- Remove Profile & check
No alert message is showing.
3- Fill Long Name & check the Name 
Correct the design of the Profile option
4- Add limit in all fields

![2](https://user-images.githubusercontent.com/88538559/228738258-ef8a1f9e-017e-484e-9f63-3f010a81c8e0.png)
![1](https://user-images.githubusercontent.com/88538559/228738263-d748fb42-de41-4152-9a82-9f430266791f.png)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by chandansinghdesigner** [comment]
Resolved
