### ISSUE TITLE
Profile - Github, Twitter & LinkedIn profile links should be passed with proper format.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#27]
1- Go to the Profile section
2- Fill  Random values in Github, Twitter & LinkedIn & check
GitHub, Twitter & LinkedIn links should be passed in the proper format.
![3](https://user-images.githubusercontent.com/88538559/228738899-76221b3a-2874-4a70-a506-93cb62e2360b.png)
![3](https://user-images.githubusercontent.com/88538559/228738954-4de3ebb8-8343-419d-a7fb-8b43600fc0e6.png)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved & closed
