### ISSUE TITLE
Dashboard - Data inconsistency is showing in the Dashboard. all heading should be shown in same text format. not captial & Small letter.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#28]
1- Open Dashboard
No tasks found & no task found is showing inside the OVERDUE WORK, Pending Ratings & Team Work.
Please correct this.

2- OVERDUE WORK is shown in the capital letter & Pending Ratings & Team Work is shown in the small letter.
![image_2023_03_30T05_36_46_160Z](https://user-images.githubusercontent.com/88538559/228741348-6b4b41db-1236-43d4-baf8-deee041b8b78.png)

**Comment by chandansinghdesigner** [comment]
resolved

**Comment by amanQA** [comment]
resolved
