### ISSUE TITLE
Project - Mandatory filed of Lead is not highlighting with Red border. Description is  not mandatory but highligting with red color.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#32]
1-  Go to the Project section 
2- Add project
3- Directly click on the submit button & check
4- Add a word limit in the description box.
![image_2023_03_30T06_39_20_876Z](https://user-images.githubusercontent.com/88538559/228750774-ec17951b-83d8-4db5-968f-9fd7188cc85e.png)

![image_2023_03_30T06_29_52_716Z](https://user-images.githubusercontent.com/88538559/228749983-22b686b3-8806-4fad-bc27-313513485f11.png)

**Comment by Adityanottysingh** [comment]
Resolved
