### ISSUE TITLE
Project - Back button & module name should be shown.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#35]
1- Go to the Project Module
2- Add project
The back button & Module name are not showing.

![image_2023_03_30T07_03_33_623Z](https://user-images.githubusercontent.com/88538559/228756140-41817625-98ec-428e-a466-cb281679fdd1.png)

**Comment by chandansinghdesigner** [comment]
resolved

**Comment by chandansinghdesigner** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
