### ISSUE TITLE
Project - Added 15 Team member but showing 13.  view more button should be shown after 3 team member's Name.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#40]
1- Go to the project Module
2- Add all Team member
3- Check
![image_2023_03_30T08_05_40_253Z](https://user-images.githubusercontent.com/88538559/228771732-439603d2-0990-458c-b47a-a3304b3ecbea.png)

**Comment by Adityanottysingh** [comment]
need discussion
