### ISSUE TITLE
Team -  Assign -  Unable to assign multiple project at a same time. Correct the design of submit button.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#41]
1- Open the Task Module
2- Click on the assign button & check

https://user-images.githubusercontent.com/88538559/228772867-7f6665b4-346e-464e-90ef-4a9c951d1d9a.mp4

![image_2023_03_30T08_10_31_643Z](https://user-images.githubusercontent.com/88538559/228773053-c142d517-ed83-4dd1-b7f7-cb9c60d283eb.png)

**Comment by chandansinghdesigner** [comment]
Resolved

**Comment by amanQA** [comment]
https://user-images.githubusercontent.com/88538559/229456781-b849c150-374d-4bf0-8a95-5c052f55c3fe.mp4
