### ISSUE TITLE
Task - Add Section - mention section in Capital letter but showing in Small letter & edit Section then Check there.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#45]
![image_2023_03_30T09_18_56_007Z](https://user-images.githubusercontent.com/88538559/228790279-0de9b4b0-df87-4f41-84c6-9568bf01929f.png)
1- Go to the Task Section
2- Add Section
3- mention the name in the Captial letter
4- Now, check the name & edit Section
5- Check Now

https://user-images.githubusercontent.com/88538559/228789221-e007a94c-353b-4a88-863a-1653a53e27d0.mp4

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
