### ISSUE TITLE
Admin - Dashboard -  Team work - Change staus is reflecting after refresh the page.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#48]
1- Login to the Admin panel
2- Go to the Dashboard
3- Change status
4- Check
5- Now, refresh the page & check

https://user-images.githubusercontent.com/88538559/228810741-a540c296-89a6-40fc-b4ea-0d836b99afdc.mp4

**Comment by Adityanottysingh** [comment]
Resolved #48
