### ISSUE TITLE
Admin - Project - Unable to add Project, delete Project & archive Project.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#50]
1- Go to the Project Module
2- Admin not able to add project

![image_2023_03_30T11_02_12_648Z](https://user-images.githubusercontent.com/88538559/228816609-4d0376bd-2765-4053-81e2-943b2d47da87.png)

![image_2023_03_30T11_06_25_116Z](https://user-images.githubusercontent.com/88538559/228817685-76b6dff0-f727-4015-96d3-601a72bfa491.png)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
https://user-images.githubusercontent.com/88538559/229460667-906434a1-141c-41ca-a16d-ac9fdd271006.mp4

**Comment by amanQA** [comment]
resolved
