### ISSUE TITLE
Team - Change button nam from add user to  Add Team.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#56]
1- Go to the Team Module
2- Check the Button Name
3- Change the button name from add a user to  Add Team.

![image_2023_03_31T05_25_33_516Z](https://user-images.githubusercontent.com/88538559/229030785-1b797458-f8f4-457d-9e79-c1d9847b3373.png)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
Resolved
