### ISSUE TITLE
Lead-  Lead can't see himself in the team section.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#62]
1- Go to the Rating Section
2- Click on the Team View
3- Check
![image_2023_03_31T06_35_40_558Z](https://user-images.githubusercontent.com/88538559/229045494-ed873e72-10ca-4a9b-b3c7-c480a43753ff.png)

**Comment by Adityanottysingh** [comment]
if current user role is lead than lead can see himself in team view listing

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
