### ISSUE TITLE
Lead - Create Task for self & select Status ongoing. now, change from the dashbaord & Check. status is not changing & panel is also getting logout.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#63]
1- Open the Lead Panel
2-  Create Task 
3- assign Task
4- Now, Change the Status of the Task from the overdue()Dashboard)
5- Refresh the page 
6- Panel is logging out.

https://user-images.githubusercontent.com/88538559/229047131-b4c7edee-7331-4ba3-a93c-d6c3b75280c4.mp4

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
