### ISSUE TITLE
Lead - Added My work, team work is showing after refresh the page. latest data should be shown on the top.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#64]
1- Open the Lead Panel
2- Add My work, Teamwork
3- Check 
4- now, refresh the Page
5- Check

https://user-images.githubusercontent.com/88538559/229053367-13c8d22d-21eb-4dfe-a85c-f00903699826.mp4

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
