### ISSUE TITLE
Lead- Correct the spelling of Completed.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#65]
1- Open lead Panel
2- Go to the Dashboard
3- Mark as a complete task inside the Teamwork.

![image_2023_03_31T06_54_37_030Z](https://user-images.githubusercontent.com/88538559/229053909-b354fffd-1186-4f5b-832c-b00f3583ce9d.png)

**Comment by Adityanottysingh** [comment]
Resolved

**Comment by amanQA** [comment]
resolved
