### ISSUE TITLE
SA, A, Lead & Contributor - Dashboard - Query - Unable to add overdue task in previous date.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#75]
1- Open the Super Admin panel
2- Add Task in Overdue Section in the Previous date.

https://user-images.githubusercontent.com/88538559/230602531-14059ab5-e283-4471-94f3-b1dcb3cd856d.mp4

**Comment by Adityanottysingh** [comment]
sir , this is a functionality we can't select date before today's date while adding a task
