### ISSUE TITLE
SA, A &  Lead - Dashboard - Pending task - Give Rating in old tasks. there is showing you are late in rating.

### ISSUE THREAD

**Issue by amanQA** [ITH-Pros/ith_tea_pro-frontend#76]
1- Open the super Admin panel
2- Go to the Pending task
3- Give Rate & check

https://user-images.githubusercontent.com/88538559/230602804-2db4f668-92be-4882-918b-d5c937b11cc9.mp4

**Comment by Adityanottysingh** [comment]
sir this is a functionality in which lead can't rate the task after 24 hour when the task mark completed and now in new modification we have remove this check and saving the log of rating
